name: authentication_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
dev_dependencies:
  firebase_auth: ^4.17.0
  firebase_core: ^2.27.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Title
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
    - family: SubTitle
      fonts:
        - asset: assets/fonts/RobotoSlab-Medium.ttf
          weight: 500
    - family: Description
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
