// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeuwHd-AorKEE8OkNp6LetZ_RZGmh1OLE',
    appId: '1:708982864267:web:b470d51dc16698ca04578e',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    authDomain: 'authentication-app-3b226.firebaseapp.com',
    storageBucket: 'authentication-app-3b226.appspot.com',
    measurementId: 'G-VGB2Z33D6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRif7UN9MKctzNruvAhy6ynVnimyxxXOw',
    appId: '1:708982864267:android:a164e38d31a9b86704578e',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    storageBucket: 'authentication-app-3b226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ36Ir0eLwjRUL9mw3ywWzi1bRakaJJes',
    appId: '1:708982864267:ios:b9bc0ec03dd8144204578e',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    storageBucket: 'authentication-app-3b226.appspot.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ36Ir0eLwjRUL9mw3ywWzi1bRakaJJes',
    appId: '1:708982864267:ios:b9bc0ec03dd8144204578e',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    storageBucket: 'authentication-app-3b226.appspot.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeuwHd-AorKEE8OkNp6LetZ_RZGmh1OLE',
    appId: '1:708982864267:web:021f962da93cca8a04578e',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    authDomain: 'authentication-app-3b226.firebaseapp.com',
    storageBucket: 'authentication-app-3b226.appspot.com',
    measurementId: 'G-2T59NK8M7N',
  );
}
